'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: System.Reflection.AssemblyVersion("1.20.0.2"),  _
 Assembly: System.Reflection.AssemblyFileVersion("1.20.0.2"),  _
 Assembly: System.Reflection.AssemblyCompany("RingDev"),  _
 Assembly: System.Reflection.AssemblyProduct("PGSwiss"),  _
 Assembly: System.Reflection.AssemblyCopyright("© 2019 RingDev")> 

