'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class WMEventStanding
    Public Property WMEventID As System.Guid
    Public Property Rank As Integer
    Public Property PPHandle As String
    Public Property Name As String
    Public Property TP As Integer
    Public Property CP As Integer
    Public Property APD As Integer
    Public Property Faction As String

    Public Overridable Property WMEvent As WMEvent

End Class
